import requests, os

# API_URL = 'https://ddragon.leagueoflegends.com/cdn/14.4.1/data/zh_TW/champion/Aatrox.json'
API_URL = 'https://ddragon.leagueoflegends.com/cdn/14.4.1/data/zh_TW/champion/'
RIOTAPI = 'RGAPI-17e9e539-6fbf-4e46-a715-25ec17bb6710'

hero_name_to_id = {
    '厄薩斯': 'Aatrox',
    '阿璃'	: 'Ahri',
    '阿卡莉': 'Akali',
    '亞歷斯塔'	: 'Alistar',
    '阿姆姆'	:  'Amumu',
    '艾妮維亞': 'Anivia',	
    '安妮'	: 'Annie',
    '亞菲利歐': 'Aphelios',
    '艾希'	: 'Ashe',
    '翱銳龍獸': 'AurelionSol',
    '阿祈爾':	 'Azir',
    '布里茨':     'Blitzcrank',
    '布蘭德':    'Brand',
    '布郎姆':   'Braum',
    '凱特琳'	: 'Caitlyn',
    '卡蜜兒'	: 'Camille',
    '卡莎碧雅':	 'Cassiopeia',
    '科加斯':	 'ChoGath',
    '庫奇'	: 'Corki',
    '達瑞斯'	: 'Darius',
    '黛安娜'	: 'Diana',
    '蒙多醫生':	 'DrMundo',
    '達瑞文':	 'Draven',
    '艾克': 'Ekko',
    '伊莉絲'	: 'Elise',
    '伊芙琳'	: 'Evelynn',
    '伊澤瑞爾':	  'Ezreal',
    '費德提克':	 'Fiddlesticks',
    '菲歐拉': 'Fiora',
    '飛斯'	: 'Fizz',
    '加里歐'	:   'Galio',
    '剛普朗克': 'Gangplank',
    '蓋倫'	:   'Garen',
    '吶兒'	:   'Gnar',
    '古拉格斯'	: 'Gragas',
    '葛雷夫'	: 'Graves',
    '赫克林'	: 'Hecarim',
    '漢默丁格'	: 'Heimerdinger',
    '伊羅旖'	: 'Illaoi',
    '伊瑞莉雅'	: 'Irelia',
    '埃爾文'	: 'Ivern',
    '嘉文四世':	 'JarvanIV',
    '賈克斯':	 'Jax',
    '杰西'	: 'Jayce',
    '燼'	: 'Jhin',
    '吉茵珂絲':	 'Jinx',
    '凱莎'	: 'Kaisa',
    '卡瑪'	: 'Kalista',
    '卡爾瑟斯'	: 'Kassadin',
    '卡薩丁'	: 'Katarina',
    '卡特蓮娜':	 'Kayle',
    '凱爾'	: 'Kayn',
    '慨影'	: 'Kennen',
    '凱能'	: 'KhaZix',
    '卡力斯':	 'Kindred',
    '鏡爪'	: 'Kled',
    '克雷德':	 'Kled',
    '寇格魔': 'KogMaw',	
    '勒布朗':	 'LeBlanc',
    '李星'	: 'LeeSin',
    '雷歐娜': 'Leona',	
    '麗珊卓': 'Lissandra',	
    '路西恩': 'Lucian',	
    '露璐'	: 'Lulu',
    '拉克絲'	: 'Lux',
    '墨菲特'	: 'Malphite',
    '馬爾札哈':	 'Malzahar',
    '茂凱'	: 'Maokai',
    '易大師':	 'MasterYi',
    '好運姐': 'MissFortune',
    '悟空'	: 'MonkeyKing',
    '魔鬥凱薩':	 'Mordekaiser',
    '魔甘娜':	 'Morgana',
    '娜米'	: 'Nami',
    '納瑟斯'	: 'Nasus',
    '納帝魯斯':	 'Nautilus',
    '妮可'	: 'Neeko',
    '奈德麗':	 'Nidalee',
    '夜曲'	: 'Nocturne',
    '努努和威朗普':	 'Nunu',
    '歐拉夫'	: 'Olaf',
    '奧莉安娜':	 'Orianna',
    '鄂爾'	: 'Ornn',
    '潘森'	: 'Pantheon',
    '波比'	: 'Poppy',
    '派克'	: 'Pyke',
    '姬亞娜':	 'Qiyana',
    '葵恩'	: 'Quinn',
    '銳空'	: 'Rakan',
    '拉姆斯'	: 'Rammus',
    '雷珂煞'	: 'RekSai',
    '雷尼克頓': 'Renekton',
    '雷葛爾':	 'Rengar',
    '雷玟'	: 'Riven',
    '藍寶'	: 'Rumble',
    '雷茲'	: 'Ryze',
    '史瓦妮':	 'Sejuani',
    '姍娜'	: 'Senna',
    '薩科'	: 'Sett',
    '慎'	: 'Shen',
    '希瓦娜':	 'Shyvana',
    '辛吉德':	 'Singed',
    '賽恩'	: 'Sion',
    '希維爾':	 'Sivir',
    '史加納':	 'Skarner',
    '索娜'	: 'Sona',
    '索拉卡':	 'Soraka',
    '斯溫'	: 'Swain',
    '賽勒斯':	 'Sylas',
    '星朵拉':	 'Syndra',
    '貪啃奇':	 'TahmKench',
    '塔莉雅': 'Taliyah',	
    '塔隆'	: 'Talon',
    '塔里克': 'Taric',
    '提摩':  'Teemo',
    '瑟雷西'	:   'Thresh',
    '崔絲塔娜'	: 'Tristana',
    '特朗德'	: 'Trundle',
    '泰達米爾': 'Tryndamere',
    '逆命'	: 'TwistedFate',
    '圖奇'	: 'Twitch',
    '烏迪爾': 'Udyr',
    '烏爾加特':	 'Urgot',
    '法洛士':	 'Varus',
    '汎'	: 'Vayne',
    '維迦'	: 'Veigar',
    '威寇茲':	 'Velkoz',
    '菲艾'	: 'Vi',
    '維克特'	: 'Viktor',
    '弗拉迪米爾':	 'Vladimir',
    '弗力貝爾':	 'Volibear',
    '剎雅': 'Warwick',
    '齊勒斯':	 'Xerath',
    '趙信':	 'XinZhao',
    '犽宿': 'Yasuo',
    '約瑞科':	 'Yorick',
    '悠咪':	 'Yuumi',
    '札克':	 'Zac',
    '劫': 'Zed',
    '希格斯':	 'Ziggs',
    '極靈':	 'Zilean',
    '柔依':	 'Zoe',
    '枷蘿': 'Zyra',
}

def get_champion_info(champion):
    champion = hero_name_to_id[champion]
    url = API_URL + champion + '.json'
    response = requests.get(url)

    if response.status_code == 200:
        # print(response.json())
        name = response.json()['data'][champion]['name']
        title = response.json()['data'][champion]['title']
        lore = response.json()['data'][champion]['lore']
    else:
        print(f"Failed to fetch champion info: HTTP {response.status_code}")
    
    return name, title, lore

